### ISSUE TITLE
Application blocked error

### ISSUE THREAD

**Issue by nancycapri** [software-engineering-project-1/digital-logic-design-exp5-team1#2]
Application Blocked error .. How to resolve this?
![untitled](https://cloud.githubusercontent.com/assets/16892166/12722994/723e33b6-c92d-11e5-8ce2-b899c1636e05.png)
@khushpreet-kaur

**Comment by khushpreet-kaur** [comment]
@nancycapri Please reply in same loop in issue #1 . Don't create different issue for the same defect.
